query doctors {
  doctors {
    _id
    username
    display_name
    email
    password
    resetToken
    resetTokenExpiry
    practice {
      _id
      name
      address
      phone_number
    }
    roles
  }
}